CREATE TABLE table1 (id INT64, name STRING(MAX), createdAt TIMESTAMP NOT NULL) PRIMARY KEY (id);
CREATE TABLE table2 (id INT64, name STRING(MAX), createdAt TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP())) PRIMARY KEY (id);
